// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkqsOvQVnAGwYnyLzXJiuKnMGNfuy3dyw',
    appId: '1:310696783894:web:9954e7bf294bf396244537',
    messagingSenderId: '310696783894',
    projectId: 'chat-app-18db9',
    authDomain: 'chat-app-18db9.firebaseapp.com',
    storageBucket: 'chat-app-18db9.appspot.com',
    measurementId: 'G-WK8P94EH35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUP3c0YxZDiklLRwOqYNCw5VbD8tgfoUI',
    appId: '1:310696783894:android:6d6e1fd4d96ee1e5244537',
    messagingSenderId: '310696783894',
    projectId: 'chat-app-18db9',
    storageBucket: 'chat-app-18db9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjejjK2BkQHVYVEjTR9_GsOd_afQDDtWw',
    appId: '1:310696783894:ios:bb034276f6848855244537',
    messagingSenderId: '310696783894',
    projectId: 'chat-app-18db9',
    storageBucket: 'chat-app-18db9.appspot.com',
    iosClientId: '310696783894-jl4b2jfddea2c4qurgbvrc4mtdosp9mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjejjK2BkQHVYVEjTR9_GsOd_afQDDtWw',
    appId: '1:310696783894:ios:bb034276f6848855244537',
    messagingSenderId: '310696783894',
    projectId: 'chat-app-18db9',
    storageBucket: 'chat-app-18db9.appspot.com',
    iosClientId: '310696783894-jl4b2jfddea2c4qurgbvrc4mtdosp9mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappFirebase',
  );
}
